---

- name: Install software updates
  apt: update_cache=yes upgrade=dist
  tags:
    - cloud

- name: Check if reboot is required
  shell: >
    if [[ -e /var/run/reboot-required ]]; then echo "required"; else echo "no"; fi
  args:
    executable: /bin/bash
  register: reboot_required
  tags:
    - cloud

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  when: reboot_required is defined and reboot_required.stdout == 'required'
  ignore_errors: true
  tags:
    - cloud

- name: Wait until SSH becomes ready...
  local_action:
    module: wait_for
    port: 22
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    delay: 10
    timeout: 320
  when: reboot_required is defined and reboot_required.stdout == 'required'
  become: false
  tags:
    - cloud

- name: Disable MOTD on login and SSHD
  replace: dest="{{ item.file }}" regexp="{{ item.regexp }}" replace="{{ item.line }}"
  with_items:
    - { regexp: '^session.*optional.*pam_motd.so.*', line: '# MOTD DISABLED', file: '/etc/pam.d/login' }
    - { regexp: '^session.*optional.*pam_motd.so.*', line: '# MOTD DISABLED', file: '/etc/pam.d/sshd' }
  tags:
    - cloud

- name: Dummy interface for services configured
  template: src=10-dummy-services.cfg.j2 dest=/etc/network/interfaces.d/10-dummy-services.cfg
  notify:
    - load dummy
    - add dummy
    - restart dummy
  tags:
    - always

- name: Dummy interface included into the network config
  lineinfile: dest=/etc/network/interfaces line='source /etc/network/interfaces.d/10-dummy-services.cfg' state=present
  notify:
    - load dummy
    - add dummy
    - restart dummy
  tags:
    - always

- meta: flush_handlers
  tags:
    - always

- set_fact:
    tools:
      - git
      - screen
      - uuid-runtime
      - coreutils
      - sendmail
      - iptables-persistent
      - cgroup-tools
      - openssl
      - sudo
      - sensible-mda
    sysctl:
      - item: net.ipv4.ip_forward
        value: 1
      - item: net.ipv4.conf.all.forwarding
        value: 1
      - item: net.ipv6.conf.all.forwarding
        value: 1
  tags:
    - always
